// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDgZ2iTXpm2vKN-EY-gS53WPBhHsQlwh4',
    appId: '1:910078203768:web:330e98d97388772d4cda8d',
    messagingSenderId: '910078203768',
    projectId: 'teakids-9254e',
    authDomain: 'teakids-9254e.firebaseapp.com',
    storageBucket: 'teakids-9254e.appspot.com',
    measurementId: 'G-B700VQ4PR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0AbXjz8lFHZCji8aWPFSYoFGmNrvYXCo',
    appId: '1:910078203768:android:2e53de4f89eb881d4cda8d',
    messagingSenderId: '910078203768',
    projectId: 'teakids-9254e',
    storageBucket: 'teakids-9254e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOmpxU1KHPu92unolqYOqVF5-04dyYSZM',
    appId: '1:910078203768:ios:154d09d427fef2914cda8d',
    messagingSenderId: '910078203768',
    projectId: 'teakids-9254e',
    storageBucket: 'teakids-9254e.appspot.com',
    iosClientId: '910078203768-dttho9js98emmj6el27t9q10jkfsm2hm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kids',
  );
}
